seed: 42

# dataset:
#     root: "../RDH_VL"
#     type: "vl"

text:
    alphabet: "# abcdefghijklmnopqrstuvwxyzšžčķģļņ_-:;,.!?()\"'"
    # "alphabet": " ˈːaäeioujlļmnņrptkķbdgģfhvszcʒšžčǯ-:;,.!?()\"'"
    character_map: [
        ["[”“]", "\""],
        ["[’]", "'"],
        ["[‐‑‒–—―⁃−]", "-"],
        ["[…]", "..."],
        ["[ç]", "c"],
        ["[àá]", "a"],
        ["[èéêë]", "e"],
        ["[îï]", "i"],
        ["[óö]", "o"],
        ["[úûü]", "u"],
        ["ā", "a_"],
        ["ē", "e_"],
        ["ī", "i_"],
        ["ū", "u_"],
        ["&", "en"]
    ]
    # normalizers: ["lowercase"]
    bos_symbols: ""
    eos_symbols: "#"

audio:
    sample_rate: 16000
    hop_length: 0.0125
    win_length: 0.050
    num_mels: 80
    fmin: 50
    fmax: 7600

model:
    encoder:
        dim_emb: 256
        # dim_pre: 128
        dim_out: 256
    decoder:
        r: 3
        dim_pre: 256
        dim_att: 128
    # output:
    #     scale: 80
    #     ref: -40

# training:
#     lr: 0.001
#     epochs: 10000
