seed: 42

dataset:
    transcript: "script"
    utt_id:
        column: 0
        re_match: "wavs/(.*).wav"
        re_path: "wavs/\\1.wav"
        re_id: "\\1"
    utt_text:
        column: 2

text:
    alphabet: "# abcdefghijklmnopqrstuvwxyzéžčķģļņ_-:;,.!?()\"'"
    # alphabet: "abcdefghijklmnopqrstuvwxyz#-:;,.!?()\"' é"             # nl
    # alphabet: "#%_abcdefghijklmnopqrstuvwxyz-:;,.!?()\"' ːˈäʒǯšžčķģļņ"  # lv (semiphonemic)
    character_map: [
        ["[”“]", "\""],
        ["[’]", "'"],
        ["[‐‑‒–—―⁃−]", "-"],
        ["[…]", "..."],
        # nl
        # ["[ç]", "c"],
        # ["[àáã]", "a"],
        # ["[èêëé]", "e"],
        # ["[îïï]", "i"],
        # ["[óö]", "o"],
        # ["[úûü]", "u"],
        # ["&", "en"],
        # en
        ["&", "and"],
        # lv
        # ["é", "ä"],
        # ["ā", "aː"],
        # ["ḗ", "äː"],
        # ["ē", "eː"],
        # ["ī", "iː"],
        # ["ū", "uː"],
        # ["ō", "oː"],
        # ["#", ""],
        # ["\\[~\\]", "%"]
    ]
    # normalizers: ["lowercase"]
    bos_symbols: ""
    eos_symbols: "#"

audio:
    sample_rate: 22050
    hop_length: 256
    win_length: 1024
    num_mels: 80
    fmin: 50
    fmax: 7600

model:
    encoder:
        type: "tacotron2"
        dim_emb: 512
        dim_out: 512
    decoder:
        type: "tacotron2prod"
        r: 1
        dim_pre: 256
        dim_att: 1024
        dim_rnn: [1024, 1024]
    postnet:
        type: tacotron2
        dim_hidden: 512
        num_layers: 3
    # output:
    #     scale: 80
    #     ref: -40

# training:
#     lr: 0.001
#     epochs: 10000
